/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author karinemellata
 */
public class TileODesignUI extends javax.swing.JFrame {
    private String hLength = "";
    private String vLength = "";
    public String numOfPlayersInGame = "";

    /**
     * Creates new form TileOUGUI
     */
    public TileODesignUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        horizontalLength = new javax.swing.JTextField();
        verticalLength = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        displayBoardButton = new javax.swing.JButton();
        createPlayerButton = new javax.swing.JButton();
        applyChangesTileButton = new javax.swing.JButton();
        applyChangesConnectionButton = new javax.swing.JButton();
        chosenPlayer = new javax.swing.JComboBox<>();
        removeTileButton = new javax.swing.JButton();
        tileType = new javax.swing.JComboBox<>();
        addTileButton = new javax.swing.JButton();
        selectPositionButton = new javax.swing.JButton();
        removeConnectionButton = new javax.swing.JButton();
        addConnectionButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        nbRollDieCard = new javax.swing.JTextField();
        nbRemoveConnectionCard = new javax.swing.JTextField();
        nbTeleportCard = new javax.swing.JTextField();
        nbLoseTurnCard = new javax.swing.JTextField();
        nbConnectTilesCard = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        loadButton = new javax.swing.JButton();
        nbOfPlayers = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel1.setText("Board:");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel2.setText("Player:");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel3.setText("Tile:");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel4.setText("Connection:");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel5.setText("Deck:");

        jLabel6.setText("Enter dimensions");

        jLabel7.setText("Enter number of players");

        jLabel8.setText("Select player");

        jLabel9.setText("Change tile type");

        horizontalLength.setBackground(new java.awt.Color(204, 204, 255));
        horizontalLength.setText("8");
        horizontalLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                horizontalLengthActionPerformed(evt);
            }
        });

        verticalLength.setBackground(new java.awt.Color(204, 204, 255));
        verticalLength.setText("8");
        verticalLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verticalLengthActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        jLabel10.setText("x");

        displayBoardButton.setBackground(new java.awt.Color(0, 0, 204));
        displayBoardButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        displayBoardButton.setText("Display Board");
        displayBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBoardButtonActionPerformed(evt);
            }
        });

        createPlayerButton.setBackground(new java.awt.Color(0, 0, 204));
        createPlayerButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        createPlayerButton.setText("Create Player");
        createPlayerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPlayerButtonActionPerformed(evt);
            }
        });

        applyChangesTileButton.setBackground(new java.awt.Color(0, 0, 204));
        applyChangesTileButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        applyChangesTileButton.setText("Apply Changes");
        applyChangesTileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangesTileButtonActionPerformed(evt);
            }
        });

        applyChangesConnectionButton.setBackground(new java.awt.Color(0, 0, 204));
        applyChangesConnectionButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        applyChangesConnectionButton.setText("Apply changes");
        applyChangesConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyChangesConnectionButtonActionPerformed(evt);
            }
        });

        chosenPlayer.setBackground(new java.awt.Color(204, 204, 255));
        chosenPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        chosenPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chosenPlayerActionPerformed(evt);
            }
        });

        removeTileButton.setBackground(new java.awt.Color(153, 153, 255));
        removeTileButton.setText("Remove Tile");
        removeTileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeTileButtonActionPerformed(evt);
            }
        });

        tileType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Regular Tile", "Action Tile", "Win Tile" }));
        tileType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tileTypeActionPerformed(evt);
            }
        });

        addTileButton.setBackground(new java.awt.Color(153, 153, 255));
        addTileButton.setText("Add Tile");
        addTileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTileButtonActionPerformed(evt);
            }
        });

        selectPositionButton.setBackground(new java.awt.Color(153, 153, 255));
        selectPositionButton.setText("Select Start Position");
        selectPositionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selectPositionButtonActionPerformed(evt);
            }
        });

        removeConnectionButton.setBackground(new java.awt.Color(153, 153, 255));
        removeConnectionButton.setText("Remove Connection");
        removeConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeConnectionButtonActionPerformed(evt);
            }
        });

        addConnectionButton.setBackground(new java.awt.Color(153, 153, 255));
        addConnectionButton.setText("Add Connection");
        addConnectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addConnectionButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Enter number of cards");

        jLabel12.setText("Roll Die");

        jLabel13.setText("Remove Connection");

        jLabel14.setText("Teleport");

        jLabel15.setText("Lose Turn");

        jLabel16.setText("Connect Tiles");

        nbRollDieCard.setBackground(new java.awt.Color(204, 204, 255));
        nbRollDieCard.setText("0");
        nbRollDieCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbRollDieCardActionPerformed(evt);
            }
        });

        nbRemoveConnectionCard.setBackground(new java.awt.Color(204, 204, 255));
        nbRemoveConnectionCard.setText("0");
        nbRemoveConnectionCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbRemoveConnectionCardActionPerformed(evt);
            }
        });

        nbTeleportCard.setBackground(new java.awt.Color(204, 204, 255));
        nbTeleportCard.setText("0");
        nbTeleportCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbTeleportCardActionPerformed(evt);
            }
        });

        nbLoseTurnCard.setBackground(new java.awt.Color(204, 204, 255));
        nbLoseTurnCard.setText("0");
        nbLoseTurnCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbLoseTurnCardActionPerformed(evt);
            }
        });

        nbConnectTilesCard.setBackground(new java.awt.Color(204, 204, 255));
        nbConnectTilesCard.setText("0");
        nbConnectTilesCard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbConnectTilesCardActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 0, 204));
        saveButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        loadButton.setBackground(new java.awt.Color(0, 0, 204));
        loadButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        nbOfPlayers.setBackground(new java.awt.Color(204, 204, 255));
        nbOfPlayers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        nbOfPlayers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nbOfPlayersActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nbRollDieCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nbRemoveConnectionCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nbTeleportCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(nbLoseTurnCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(87, 87, 87)
                                .addComponent(nbConnectTilesCard, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(46, 46, 46)
                                .addComponent(jLabel16)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(61, 61, 61)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)
                                        .addComponent(addTileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(removeTileButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(addConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(chosenPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(selectPositionButton, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(removeConnectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(25, 25, 25)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(nbOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(horizontalLength, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(10, 10, 10)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(verticalLength, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(6, 6, 6)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applyChangesConnectionButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayBoardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createPlayerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(applyChangesTileButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(saveButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(horizontalLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verticalLength, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(displayBoardButton))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(createPlayerButton)
                    .addComponent(chosenPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(selectPositionButton)
                    .addComponent(nbOfPlayers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel9)
                    .addComponent(applyChangesTileButton)
                    .addComponent(tileType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addTileButton)
                    .addComponent(removeTileButton))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(applyChangesConnectionButton)
                    .addComponent(removeConnectionButton)
                    .addComponent(addConnectionButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(nbRollDieCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbRemoveConnectionCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbTeleportCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbLoseTurnCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nbConnectTilesCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(loadButton)
                .addContainerGap(478, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void horizontalLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_horizontalLengthActionPerformed
        hLength = horizontalLength.getText();
    }//GEN-LAST:event_horizontalLengthActionPerformed

    private void verticalLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verticalLengthActionPerformed
        vLength = horizontalLength.getText();
    }//GEN-LAST:event_verticalLengthActionPerformed

    private void displayBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBoardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_displayBoardButtonActionPerformed

    private void createPlayerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPlayerButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPlayerButtonActionPerformed

    private void applyChangesTileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangesTileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyChangesTileButtonActionPerformed

    private void applyChangesConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyChangesConnectionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_applyChangesConnectionButtonActionPerformed

    private void chosenPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chosenPlayerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chosenPlayerActionPerformed

    private void removeTileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeTileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeTileButtonActionPerformed

    private void tileTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tileTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tileTypeActionPerformed

    private void addTileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTileButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addTileButtonActionPerformed

    private void selectPositionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selectPositionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_selectPositionButtonActionPerformed

    private void removeConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeConnectionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_removeConnectionButtonActionPerformed

    private void addConnectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addConnectionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addConnectionButtonActionPerformed

    private void nbRollDieCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbRollDieCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbRollDieCardActionPerformed

    private void nbRemoveConnectionCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbRemoveConnectionCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbRemoveConnectionCardActionPerformed

    private void nbTeleportCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbTeleportCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbTeleportCardActionPerformed

    private void nbLoseTurnCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbLoseTurnCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbLoseTurnCardActionPerformed

    private void nbConnectTilesCardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbConnectTilesCardActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nbConnectTilesCardActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loadButtonActionPerformed

    private void nbOfPlayersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nbOfPlayersActionPerformed
        String nbOfPlayersChosen = (String) nbOfPlayers.getSelectedItem();
        switch (nbOfPlayersChosen) { //Setting number of pkayers in game, to send to controller
            case "2":
                numOfPlayersInGame = "2";
                break;
            case "3":
                numOfPlayersInGame = "3";
                break;
            case "4":
                numOfPlayersInGame = "4";
                break;
        }
        if (nbOfPlayers.getSelectedItem()== "2") { //Setting value of combo box for choosing a player to defined number of players
            chosenPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1", "2"}));}
        else if(nbOfPlayers.getSelectedItem()== "3"){
            chosenPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"1", "2", "3"}));}
        else{
            chosenPlayer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        }
    }//GEN-LAST:event_nbOfPlayersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TileODesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TileODesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TileODesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TileODesignUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TileODesignUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addConnectionButton;
    private javax.swing.JButton addTileButton;
    private javax.swing.JButton applyChangesConnectionButton;
    private javax.swing.JButton applyChangesTileButton;
    private javax.swing.JComboBox<String> chosenPlayer;
    private javax.swing.JButton createPlayerButton;
    private javax.swing.JButton displayBoardButton;
    private javax.swing.JTextField horizontalLength;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton loadButton;
    private javax.swing.JTextField nbConnectTilesCard;
    private javax.swing.JTextField nbLoseTurnCard;
    private javax.swing.JComboBox<String> nbOfPlayers;
    private javax.swing.JTextField nbRemoveConnectionCard;
    private javax.swing.JTextField nbRollDieCard;
    private javax.swing.JTextField nbTeleportCard;
    private javax.swing.JButton removeConnectionButton;
    private javax.swing.JButton removeTileButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton selectPositionButton;
    private javax.swing.JComboBox<String> tileType;
    private javax.swing.JTextField verticalLength;
    // End of variables declaration//GEN-END:variables
}
